# Generated by Django 2.2.6 on 2019-10-07 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.Delivery_Agent'),
        ),
    ]
