# Generated by Django 2.2.6 on 2019-10-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20191007_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
