# Generated by Django 2.2.6 on 2019-10-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20191007_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
