# Generated by Django 2.2.6 on 2019-10-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_delivery_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_agent',
            name='suit_length',
            field=models.IntegerField(default=0),
        ),
    ]
