# Generated by Django 2.2.6 on 2019-10-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20191007_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='total_distance',
            field=models.IntegerField(default=0),
        ),
    ]
